//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nucleus_remote_updater.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class UpdaterSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UpdaterSettings defaultInstance = ((UpdaterSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UpdaterSettings())));
        
        public static UpdaterSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nrs.backend.pcsmw.de/system/update/")]
        public string UpdateBaseUrl {
            get {
                return ((string)(this["UpdateBaseUrl"]));
            }
            set {
                this["UpdateBaseUrl"] = value;
            }
        }
    }
}
